### ISSUE TITLE
earliest_first not respected

### ISSUE THREAD

**Issue by richiela** [ripple/ripple-rest#249]
Options object still has old variable name:

    ledger_index_max: undefined,
    earliest_first: false,
    exclude_failed: true,
    min: '10',
    max: '10',

currently

    return compareTransactions(first, second, options.earliestFirst);

I've changed our code to be below.  Not sure if the intent was the change the name in the options object 

    return compareTransactions(first, second, options.earliest_first);

**Comment by lumberj** [comment]
Is this still an issue?
