### ISSUE TITLE
getting NetworkError when using ripple-rest with rippled in standalone mode

### ISSUE THREAD

**Issue by dericabel** [ripple/ripple-rest#252]
I have a rippled in standalone mode for some development purposes.  When I try and use ripple-rest with that rippled instance I get 

``` json
{
  "success": false,
  "error_type": "connection",
  "error": "Cannot connect to rippled"
}
```
on the debug console for ripple-rest I get 

2015-01-02T15:41:21.402Z - info: GET /v1/server
2015-01-02T15:41:21.403Z - error: NetworkError
    at Object.<anonymous> (/home/ubuntu/ripple-rest/lib/errors.js:18:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/ripple-rest/api/info.js:6:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
2015-01-02T15:41:21.403Z - info: GET /v1/server 502 1.227 ms - 92

Prior to that I do see that it is connected to rippled:

2015-01-02T15:40:53.545Z - info: [RIPD] Connected to rippled server: ws://localhost:5006 (n9KjPM5SPU4MLpXNdHpNGuWYLRPEmF5q9tJCnnTNxk1o1s2HD9uF)
[2015-01-02T15:40:53.545Z] remote: response:
``` json
{
  "id": 0,
  "result": {
    "fee_base": 10,
    "fee_ref": 10,
    "hostid": "MIND",
    "ledger_hash": "484D962F3E18C37C6F6FCAE6F6A0DA064C285B0360656D8DBECFEC1FE0798A29",
    "ledger_index": 2,
    "ledger_time": 473376990,
    "load_base": 256,
    "load_factor": 256,
    "pubkey_node": "n9KjPM5SPU4MLpXNdHpNGuWYLRPEmF5q9tJCnnTNxk1o1s2HD9uF",
    "random": "4EF74B5A0B3E3A185A13629E270992A738D2E18E7F25C6E5D71F31E3999CC6C1",
    "reserve_base": 200000000,
    "reserve_inc": 50000000,
    "server_status": "full",
    "stand_alone": true,
    "validated_ledgers": "1-2"
  },
  "status": "success",
  "type": "response"
}
```

If I connect directly to the websocket interface of my rippled interface and issue a server_info I get:
``` json
{
    "id": 1,
    "result": {
        "info": {
            "build_version": "0.26.4-sp3",
            "complete_ledgers": "1-2",
            "hostid": "MIND",
            "io_latency_ms": 1,
            "last_close": {
                "converge_time_s": 15,
                "proposers": 0
            },
            "load_factor": 1,
            "peers": 0,
            "pubkey_node": "n9KjPM5SPU4MLpXNdHpNGuWYLRPEmF5q9tJCnnTNxk1o1s2HD9uF",
            "server_state": "full",
            "validated_ledger": {
                "age": 151769,
                "base_fee_xrp": 0.00001,
                "hash": "484D962F3E18C37C6F6FCAE6F6A0DA064C285B0360656D8DBECFEC1FE0798A29",
                "reserve_base_xrp": 200,
                "reserve_inc_xrp": 50,
                "seq": 2
            },
            "validation_quorum": 3
        }
    },
    "status": "success",
    "type": "response"
}
```

Every websocket call works when I use a websocket client and connect directly to rippled but with ripple-rest all the calls return cannot connect to rippled.

It seems as though ripple-rest won't work with a rippled in standalone mode.  It would be nice to be able to develop against a standalone rippled instead of connecting to the ripple network.

**Comment by dericabel** [comment]
I have tested my rippled in standalone mode with ripple-lib and all the same calls above work just fine, so this is an issue with ripple-rest.

**Comment by dericabel** [comment]
Diving into the code a little more I can see that there is a function called ensureConnected that checks a property on the ripple-lib remote.getServer() object.  The property is _lastLedgerClose which is NaN so it will always return false.  So this doesn't appear to be a bug, but I'm not sure how to get rippled when in standalone mode to return a useful value.

**Comment by wltsmrz** [comment]
You'll have to close ledgers manually. ripple-rest waits for a ledger close before determining that the connection is good (as you discovered)

**Comment by dericabel** [comment]
According to the rippled docs -

ledger_accept
To support software testing, in stand alone mode, this command closes the current ledger and return the new current ledger index. This command is only available with admin access.

I've tried this and rippled-rest still fails.

**Comment by dericabel** [comment]
Looks like ledger_accept works but if a long enough of time passes before issuing another ledger_accept the _lastLedgerClose value returns to NaN.  I set up a timed process to issue ledger_accept every 5 seconds and that seems to solve my issue.

Thanks, this actually lead me into the right direction.

**Comment by wltsmrz** [comment]
Yes, a ledger should close within 30s
