### ISSUE TITLE
Quick start docs

### ISSUE THREAD

**Issue by s1monfarrow** [ripple/ripple-rest#294]
The docs say to run "node server.js"

I think that it should probably be "node server/server.js"

I tried running index.js but that didn't want to work, the server.js file in the sub directory seemed to work nicely though.

**Comment by lumberj** [comment]
Docs should say `npm start`. Thank you, I'll update

**Comment by SyRenity** [comment]
This quite stumbled me as well, suggesting updating the quick start soon :)
https://ripple.com/build/ripple-rest/#quick-start
