### ISSUE TITLE
Trustlines + Balances limited to 200

### ISSUE THREAD

**Issue by metoro** [ripple/ripple-rest#301]
Both the trustline and balances endpoints appear to be limited to 200 results (regardless of the setting of 'limit'). I know this is now an old bug, and forgive me for not finding the issue, however it's now months later, and a fix is still not in the master branch. We need this functionality to reconcile our accounts.

**Comment by lumberj** [comment]
See documentation for paginating through results: https://ripple.com/build/ripple-rest/#get-account-balances. Let me know if you'd like a more concrete example

**Comment by metoro** [comment]
Apologies if I am missing something. The docs seem to indicate that setting limit=all will give all results, but this is not the case as far as I can see (though it works fine on the public RL REST API)

**Comment by lumberj** [comment]
What rippled are you connecting to?

**Comment by metoro** [comment]
fs1

**Comment by lumberj** [comment]
Can you please provide more details of the bug, and the transactions that are missing from the rest API call? You mention it works fine on the public RL REST API, but not when you run locally?

**Comment by metoro** [comment]
Ok, so - running latest REST API code (master), connecting to fs1. The results are limited to 200 items (when the actual number is over 400). Run the same command on api.ripple.com, and it works.

This has been an outstanding issue for many weeks now. I have been patiently waiting for a fix, but it is still not there...

**Comment by metoro** [comment]
Yep, no difference using s1.

**Comment by lumberj** [comment]
What is fs1? What is the command you are running? 200 is the max limit before you need to paginate through results.

**Comment by metoro** [comment]
According to the docs, you can put limit=all and get all results (no paging). This works on api.ripple.com, but not when running the master branch of the REST code.

**Comment by lumberj** [comment]
We are running the master branch in production. Can you please share the endpoint you are hitting?

**Comment by metoro** [comment]
Urgh. N.mind, seems my R.REST code wasn't up to date after all. Working now.
