### ISSUE TITLE
payment steps

### ISSUE THREAD

**Issue by landoyjx** [ripple/ripple-rest#307]
Why is payment separated as so many steps?
Firstly prepare payment, then submit payment, lastly confirm it.
Why not is just one step?

**Comment by lumberj** [comment]
Check out: https://ripple.com/build/reliable-transaction-submission/#ripple-rest-submitting-and-verifying-payments

> Applications should persist a record of a transaction before submitting it, in order to recover from a catastrophic failure such as a power outage
