### ISSUE TITLE
Order transaction error: Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by ww3456** [ripple/ripple-rest#384]
For transaction [04DB1D743926DF6F2C3855C95FBB877186F55E9A3B25B1B491F55CB84594FC88](https://api.ripple.com/v1/accounts/rapido5rxPmP4YkMZZEeXSHqWefxHEkqv6/orders/04DB1D743926DF6F2C3855C95FBB877186F55E9A3B25B1B491F55CB84594FC88) the REST server returns the error below. 
```
{
  "success": false,
  "error": "Cannot read property 'currency' of undefined",
  "error_type": "transaction"
}
```

While [https://ripple.com/build/websocket-tool/#tx](https://ripple.com/build/websocket-tool/#tx) shows an apparently valid transaction. 

Is this a problem with the Ripple REST server?

**Comment by lumberj** [comment]
Looking into it

**Comment by lumberj** [comment]
This should fix it, https://github.com/ripple/ripple-rest/pull/385

**Comment by ww3456** [comment]
Yes, that has fixed it. Thanks very much.
