### ISSUE TITLE
Destination balance changes: Issuer ?

### ISSUE THREAD

**Issue by njmurarka** [ripple/ripple-rest#392]
So I am looking at TX:

5B6D93935862E393DFCCB0267A0BC77D2D10600ADBCF724C1C927FD061CBE341

If I look at the following:

["payment"]["destination_balance_changes"][0]["issuer"]

The issuer here might be the Market Maker that enabled the tx, where XRP was converted to CAD to be sent to the destination Ripple address. But the issuer is actually Bluzelle.

So question then is -- how do we, looking at this tx, get the actual issuer of the currency (CAD) being sent?

Incorrect issuer:

rQE5Z3FgVnRMbVfS6xiVQFgB4J3X162FVD

Correct issuer:

raBDVR7JFq3Yho2jf7mcx36sjTwpRJJrGU

Indeed, this tx refers to "raBDVR7JFq3Yho2jf7mcx36sjTwpRJJrGU" as the recipient, but we need to validate the issuer as being raBDVR7JFq3Yho2jf7mcx36sjTwpRJJrGU in the destination balance changes.

**Comment by njmurarka** [comment]
I noted that the field is being renamed to "counterparty" but I am unsure this relates to this issue -- right now, the counterparty field is undefined anyways in my copy of ripple-rest.

**Comment by njmurarka** [comment]
Here is a quick way to see the ripple-rest output:

https://api.ripple.com/v1/accounts/raBDVR7JFq3Yho2jf7mcx36sjTwpRJJrGU/payments/5B6D93935862E393DFCCB0267A0BC77D2D10600ADBCF724C1C927FD061CBE341

**Comment by clark800** [comment]
The balance changes should use `counterparty` instead of `issuer`, but `issuer` has been kept for backwards compatibility. See this blog post for more information: https://ripple.com/dev-blog/calculating-balance-changes-for-transaction/#counterparty-vs-issuer
